NONE = "none"
CRIMSON = "Crimson"
SKY_BLUE = "Sky Blue"
PINK = "Pink"
ORANGE = "Orange"
COBALT = "Cobalt"
BURNT_SIENNA = "Burnt Sienna"
TITANIUM_WHITE = "Titanium White"
GREY = "Grey"
SAFFRON = "Saffron"
LIME = "Lime"
FOREST_GREEN = "Forest Green"
BLACK = "Black"
PURPLE = "Purple"
COLORS = [CRIMSON, SKY_BLUE, PINK, ORANGE, COBALT, BURNT_SIENNA, TITANIUM_WHITE, GREY, SAFFRON, LIME, FOREST_GREEN,
          BLACK, PURPLE]
